version: '3.9'

services:
  secure_file_service:
    build:
      context: secure_file_service
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  secure_file_ui:
    build:
      context: secure_file_ui
      dockerfile: dockerfile
    ports:
      - "3000:3000"