# Generated by Django 5.1.4 on 2025-01-02 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharablelink',
            old_name='parentFile',
            new_name='parent_file',
        ),
        migrations.AddField(
            model_name='sharablelink',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
