# Generated by Django 5.1.4 on 2025-01-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_parentfile_sharablelink_parent_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharablelink',
            name='permission',
            field=models.CharField(choices=[('VIEW', 'VIEW'), ('DOWNLOAD', 'DOWNLOAD')], max_length=10),
        ),
    ]
