FROM python:3.13.1

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install -r requirements.txt
RUN pip install debugpy

# CMD gunicorn --workers 1 --bind 0.0.0.0:8000 secure_file_service.wsgi:application
CMD python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
